### ISSUE TITLE
Map: Show Drivers at all times

### ISSUE THREAD

**Issue by richardwestenra** [voteamerica/voteamerica.github.io#335] opened 2017-11-11 22:32 UTC
Once vehicles accept an assignment, they disappear from the map and never reappear. To people visiting the map it will appear that we have no drivers in the area when in fact we do.

Can we show all drivers as visible, as long as they are working in their timeframe, and have them disappear when they are off duty?

Perhaps drivers could be color-coded, e.g. ![Green](https://placehold.it/15/09c100/000000?text=+)=Available, ![Yellow](https://placehold.it/15/ffd800/000000?text=+)=Have Passenger and ![Red](https://placehold.it/15/d40000/000000?text=+)=Off Duty. Since we know when a driver has a passenger, the color-coding should be possible. (Currently all operators are women and none are color-blind).

**Comment by jkbits1** [comment] 2018-09-19 23:43
Related to #354

**Comment by jkbits1** [comment] 2018-10-29 22:14
Fixed by #364 

@richardwestenra closing this as the main part of the issue is addressed. However, we are now maintaining a gitBook of useful comments and discussions and the colour-coding suggestion is definitely worth keeping for later review.

That's useful information about the relevance of colour-blindness. Some operators do have visual impairments, so there may be issues with contrast.

@stephenscapelliti can you add this the gitBook, please?

**Closed by jkbits1** 2018-10-29 22:14 UTC
Labels: map, pending review
