### ISSUE TITLE
Change text at the top of the driver and rider signup forms

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#92] opened 2016-10-10 19:32 UTC
**Riders:**
Need a ride to claim your vote?
Some of our riders need to get to the polls - either on polling day or during early voting. Others need to travel to get a photo I.D.
Just fill in this form! We'll try to connect you with a driver.
_[HOW DOES IT WORK?] button hyperlinks to explanation page_

**Drivers:**
Sign up to give a fellow American a ride to claim their vote.
Offer to drive someone to the polls or, if you live in a state where you need to show voter I.D., drive somebody to go and get one.
Just fill in this form! We'll try to connect you with someone who needs a ride.
_[HOW DOES IT WORK?] button hyperlinks to explanation page_

**Comment by richardwestenra** [comment] 2016-10-18 11:19
Note that the two intro boxes have a minimum height set in the CSS to ensure that they're the same height, so when updating the text, please remember to check/update the `min-height` value as well 🙂

**Comment by cyberplanner** [comment] 2016-10-20 13:13
I'll do this one :)

**Comment by richardwestenra** [comment] 2016-10-20 13:20
@cyberplanner Hey, sorry, I think this is a duplicate of #130, which was completed yesterday! There's no longer any need to change this copy (right @sasjkia?)

**Closed by richardwestenra** 2016-10-20 13:20 UTC
Labels: beginner

**Comment by cyberplanner** [comment] 2016-10-20 13:30
Thanks @richardwestenra... good thing I said something first :+1:

**Comment by richardwestenra** [comment] 2016-10-20 13:35
Phew :)
